server:
  port: 30334
spring:
  application:
    name: service-auth
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:30333/dbhw
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    consul:
      discovery:
        service-name: service-auth
        heartbeat:
          enabled: true
      host: localhost
      port: 30332
management:
  endpoint:
    health:
      show-details: always