server:
  port: 8092
spring:
  application:
    name: service-zuul
  cloud:
    consul:
      discovery:
        service-name: service-zuul
      host: localhost
      port: 8500
management:
  endpoint:
    health:
      show-details: always
zuul:
  routes:
    feign:
      path: /api-feign/**
      serviceId: service-ribbon
    bookstore:
      path: /api-bookstore/**
      serviceId: service-bookstore
    wordladder:
      path: /wordladder/*
      serviceId: service-wordladder
